language: rust
rust: stable

# We need somewhat recent libclang packages
dist: bionic

install:
  - rustup target add thumbv7em-none-eabi
  - rustup target add thumbv6m-none-eabi
  - rustup component add rustfmt

stages:
  - test
  - name: deploy
    if: branch = master AND type = push

jobs:
  include:
    - stage: test
      before_script:
        - sudo apt-get update
        - sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi libclang-dev
      script:
        - ci/test.sh
        - ci/upload-docs.sh

notifications:
  email:
    on_success: never
