language: rust
rust: stable

install:
  - rustup target add thumbv7em-none-eabi
  - rustup target add thumbv6m-none-eabi
  - rustup component add rustfmt

stages:
  - test
  - name: deploy
    if: branch = master AND type = push

jobs:
  include:
    - stage: test
      before_script:
        - sudo apt-get update
        - sudo apt-get install gcc-arm-none-eabi -y
      script:
        - ci/test.sh
        - ci/upload-docs.sh

notifications:
  email:
    on_success: never
