[package]
authors = ["Jonas Schievink <jonasschievink@gmail.com>"]
description = "An embedded BLE stack"
categories = ["embedded", "no-std"]
keywords = ["arm", "cortex-m", "bluetooth", "low", "energy"]
repository = "https://github.com/jonas-schievink/rubble/"
license = "0BSD"
name = "rubble"
version = "0.0.0"
edition = "2018"

[dependencies]
byteorder = { version = "1.3.1", default-features = false }
bitflags = "1.0.4"
uuid = { version = "0.7.2", default-features = false }
bbqueue = "0.3.2"

# If the `log` feature is enabled, the `log` crate's macros will be called at various points to dump
# packets, state, and events. By default, it is disabled.
[dependencies.log]
git = "https://github.com/rust-lang-nursery/log.git"
rev = "75043f9"
optional = true
